package com.example.studentv1.controller;

import com.example.studentv1.model.Student;
import com.example.studentv1.repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@RestController
public class StudentRestController {

    @Autowired
    StudentRepository studentRepository;

    @GetMapping("/students")
    public List<Student> getStudent() {
        return studentRepository.findAll();
    }

        @GetMapping("/autostudent")
        public List<Student> autoStudent() {
            Student std = new Student();
            std.setBornDate(LocalDate.now());
            std.setBornTime(LocalTime.now());
            List<Student> lst = studentRepository.findAll();
            std.setName("Autogenerated size=" + lst.size());
            studentRepository.save(std);
            System.out.println("Student saved");
            return studentRepository.findAll();
        }
}
